"""init schema

Revision ID: 7a88f4834311
Revises: 
Create Date: 2026-08-02 10:32:17.369770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a88f4834311'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='对象类型'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='对象ID'),
    sa.Column('detail', sa.Text(), nullable=True, comment='详情'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='来源IP'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('consultation_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='患者用户ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('summary_id', sa.Integer(), nullable=True, comment='问诊总结ID（归档来源）'),
    sa.Column('archived_type', sa.String(length=20), nullable=False, comment='归档类型 reviewed/awaiting'),
    sa.Column('record_summary', sa.Text(), nullable=True, comment='归档摘要'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_records_conversation_id'), 'consultation_records', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_consultation_records_patient_id'), 'consultation_records', ['patient_id'], unique=False)
    op.create_table('consultation_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='医学生用户ID'),
    sa.Column('chief_complaint', sa.String(length=200), nullable=False, comment='主诉（≤100字）'),
    sa.Column('present_illness', sa.Text(), nullable=False, comment='现病史'),
    sa.Column('past_illness', sa.Text(), nullable=True, comment='既往史'),
    sa.Column('consultation_process', sa.Text(), nullable=True, comment='问诊过程'),
    sa.Column('initial_diagnosis', sa.String(length=300), nullable=False, comment='初步判断'),
    sa.Column('treatment_advice', sa.Text(), nullable=False, comment='诊疗建议'),
    sa.Column('status', sa.Enum('draft', 'pending', 'passed', 'rejected', name='summarystatus', native_enum=False), server_default='draft', nullable=False, comment='审核状态'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='审核医生ID'),
    sa.Column('reviewed_at', sa.String(length=30), nullable=True, comment='审核时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_summaries_conversation_id'), 'consultation_summaries', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_consultation_summaries_student_id'), 'consultation_summaries', ['student_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='患者用户ID'),
    sa.Column('student_id', sa.Integer(), nullable=True, comment='医学生用户ID'),
    sa.Column('doctor_id', sa.Integer(), nullable=True, comment='介入/直接问诊医生ID'),
    sa.Column('status', sa.Enum('active', 'ended', name='conversationstatus', native_enum=False), server_default='active', nullable=False, comment='会话状态'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('summary_triggered', sa.Boolean(), server_default='0', nullable=False, comment='已触发总结填报'),
    sa.Column('end_requester_id', sa.Integer(), nullable=True, comment='发起结束请求的用户ID'),
    sa.Column('end_confirm_id', sa.Integer(), nullable=True, comment='确认结束的用户ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_doctor_id'), 'conversations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_conversations_patient_id'), 'conversations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_conversations_student_id'), 'conversations', ['student_id'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('license_no', sa.String(length=50), nullable=False, comment='执业医师证书编号'),
    sa.Column('practice_scope', sa.String(length=100), nullable=False, comment='执业范围'),
    sa.Column('organization', sa.String(length=200), nullable=False, comment='执业机构'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='职称'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=True)
    op.create_table('health_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='患者用户ID'),
    sa.Column('metric_type', sa.Enum('bp', 'bg', 'weight', name='metrictype', native_enum=False), nullable=False, comment='指标类型'),
    sa.Column('value_primary', sa.Float(), nullable=False, comment='主值（收缩压/血糖值/体重）'),
    sa.Column('value_secondary', sa.Float(), nullable=True, comment='次值（舒张压）'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('measured_at', sa.DateTime(), nullable=False, comment='测量时间'),
    sa.Column('is_abnormal', sa.Boolean(), server_default='0', nullable=False, comment='是否超出正常范围'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源 patient/student/doctor'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_data_patient_id'), 'health_data', ['patient_id'], unique=False)
    op.create_table('health_reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='患者用户ID'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='创建者用户ID'),
    sa.Column('creator_role', sa.String(length=20), nullable=False, comment='创建者角色 doctor/student'),
    sa.Column('reminder_type', sa.Enum('medication', 'measurement', 'follow_up', 'lifestyle', name='remindertype', native_enum=False), nullable=False, comment='提醒类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='提醒内容'),
    sa.Column('detail', sa.Text(), nullable=True, comment='类型扩展信息（药品名称、用法用量、测量指标、复诊科室等）'),
    sa.Column('cycle', sa.Enum('once', 'daily', 'weekly', 'monthly', name='remindercycle', native_enum=False), nullable=False, comment='周期模式'),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False, comment='调度表达式（cron）'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='生效时间（单次为执行时间）'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('status', sa.Enum('active', 'ended', 'paused', name='reminderstatus', native_enum=False), server_default='active', nullable=False, comment='状态'),
    sa.Column('push_enabled', sa.Boolean(), server_default='1', nullable=False, comment='推送开关'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_reminders_patient_id'), 'health_reminders', ['patient_id'], unique=False)
    op.create_table('medical_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='患者用户ID'),
    sa.Column('history_type', sa.Enum('family', 'allergy', 'past', name='historytype', native_enum=False), nullable=False, comment='病史类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='病史内容'),
    sa.Column('source_user_id', sa.Integer(), nullable=True, comment='来源用户（协同维护）'),
    sa.Column('source_role', sa.String(length=20), nullable=False, comment='来源角色'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号（溯源）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_histories_patient_id'), 'medical_histories', ['patient_id'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='患者用户ID'),
    sa.Column('medication_name', sa.String(length=100), nullable=False, comment='药品名称'),
    sa.Column('dosage', sa.String(length=100), nullable=True, comment='用量'),
    sa.Column('taken_at', sa.DateTime(), nullable=False, comment='服用时间（用药时间轴）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_logs_patient_id'), 'medication_logs', ['patient_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='发送者用户ID'),
    sa.Column('sender_role', sa.String(length=20), nullable=False, comment='发送者角色'),
    sa.Column('msg_type', sa.Enum('text', 'image', 'voice', 'file', 'system', name='messagetype', native_enum=False), nullable=False, comment='消息类型'),
    sa.Column('content', sa.Text(), nullable=True, comment='文本内容/文件URL/语音URL'),
    sa.Column('translated_text', sa.Text(), nullable=True, comment='互转后的目标语言文本'),
    sa.Column('target_audio_url', sa.String(length=500), nullable=True, comment='互转后的合成语音URL'),
    sa.Column('status', sa.String(length=20), server_default='sent', nullable=False, comment='发送状态 sent/failed'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='已读时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conv_time', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('gender', sa.String(length=10), nullable=False, comment='性别'),
    sa.Column('birth_date', sa.String(length=20), nullable=False, comment='出生日期'),
    sa.Column('ethnicity', sa.String(length=30), nullable=False, comment='民族（必填，用于语言适配）'),
    sa.Column('address', sa.String(length=300), nullable=True, comment='住址'),
    sa.Column('allergy_history', sa.Text(), nullable=True, comment='过敏史'),
    sa.Column('language_pref', sa.String(length=10), server_default='zh', nullable=False, comment='语言偏好 zh/yi'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_profiles_user_id'), 'patient_profiles', ['user_id'], unique=True)
    op.create_table('plan_todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='计划ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='医学生用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='待办标题'),
    sa.Column('due_at', sa.DateTime(), nullable=True, comment='截止时间'),
    sa.Column('priority', sa.String(length=10), nullable=False, comment='优先级 high/medium/low'),
    sa.Column('status', sa.Enum('pending', 'done', 'overdue', 'deferred', name='todostatus', native_enum=False), server_default='pending', nullable=False, comment='状态'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_todos_plan_id'), 'plan_todos', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_todos_student_id'), 'plan_todos', ['student_id'], unique=False)
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False, comment='提醒ID'),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='患者用户ID'),
    sa.Column('sent_at', sa.DateTime(), nullable=False, comment='发送时间'),
    sa.Column('delivery_status', sa.String(length=20), nullable=False, comment='送达状态 sent/failed'),
    sa.Column('feedback', sa.String(length=20), nullable=True, comment='患者反馈 done/later/none'),
    sa.Column('feedback_at', sa.DateTime(), nullable=True, comment='反馈时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_logs_patient_id'), 'reminder_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_reminder_id'), 'reminder_logs', ['reminder_id'], unique=False)
    op.create_table('review_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.Enum('summary', 'plan', name='reviewtargettype', native_enum=False), nullable=False, comment='审核对象类型'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='审核对象ID'),
    sa.Column('reviewer_id', sa.Integer(), nullable=False, comment='审核医生ID'),
    sa.Column('result', sa.Enum('pass', 'reject', name='reviewresult', native_enum=False), nullable=False, comment='审核结果'),
    sa.Column('comment', sa.Text(), nullable=True, comment='审核意见（驳回必填）'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='提交人ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_records_target_id'), 'review_records', ['target_id'], unique=False)
    op.create_table('score_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='医学生用户ID'),
    sa.Column('summary_id', sa.Integer(), nullable=True, comment='关联总结ID'),
    sa.Column('reviewer_id', sa.Integer(), nullable=False, comment='评分医生ID'),
    sa.Column('q_consultation', sa.Integer(), nullable=False, comment='问诊规范性得分'),
    sa.Column('q_history', sa.Integer(), nullable=False, comment='病史采集完整性得分'),
    sa.Column('q_communication', sa.Integer(), nullable=False, comment='沟通能力得分'),
    sa.Column('q_summary', sa.Integer(), nullable=False, comment='总结质量得分'),
    sa.Column('total', sa.Integer(), nullable=False, comment='总分（百分制）'),
    sa.Column('grade', sa.String(length=10), nullable=False, comment='等级 优秀/良好/合格/不合格'),
    sa.Column('comment', sa.Text(), nullable=False, comment='评语（必填）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_records_student_id'), 'score_records', ['student_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('school', sa.String(length=200), nullable=False, comment='院校'),
    sa.Column('major', sa.String(length=100), nullable=False, comment='专业'),
    sa.Column('grade', sa.String(length=50), nullable=False, comment='年级'),
    sa.Column('student_no', sa.String(length=50), nullable=False, comment='学号'),
    sa.Column('mentor_doctor_id', sa.Integer(), nullable=True, comment='带教医生用户ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='医学生用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='计划名称'),
    sa.Column('period', sa.String(length=50), nullable=False, comment='计划周期'),
    sa.Column('goal', sa.Text(), nullable=False, comment='目标说明'),
    sa.Column('status', sa.Enum('draft', 'pending', 'passed', 'rejected', name='planstatus', native_enum=False), server_default='draft', nullable=False, comment='审核状态'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_student_id'), 'training_plans', ['student_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('role', sa.Enum('doctor', 'student', 'patient', 'admin', name='userrole', native_enum=False), nullable=False, comment='角色（唯一绑定）'),
    sa.Column('status', sa.Enum('pending', 'active', 'rejected', 'disabled', name='userstatus', native_enum=False), server_default='pending', nullable=False, comment='账号状态'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('reject_reason', sa.String(length=500), nullable=True, comment='审核驳回原因'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最近登录时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('voice_translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True, comment='关联消息ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('source_lang', sa.String(length=10), nullable=False, comment='源语言 zh/yi'),
    sa.Column('target_lang', sa.String(length=10), nullable=False, comment='目标语言 zh/yi'),
    sa.Column('source_text', sa.Text(), nullable=True, comment='源语言文本（STT 结果）'),
    sa.Column('target_text', sa.Text(), nullable=True, comment='目标语言文本（翻译结果）'),
    sa.Column('source_audio_url', sa.String(length=500), nullable=True, comment='源语音URL'),
    sa.Column('target_audio_url', sa.String(length=500), nullable=True, comment='合成语音URL（TTS）'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='识别置信度'),
    sa.Column('term_hit_count', sa.Integer(), nullable=False, comment='医疗术语词典命中数'),
    sa.Column('status', sa.Enum('success', 'failed', 'degraded', name='translationstatus', native_enum=False), server_default='success', nullable=False, comment='转换状态'),
    sa.Column('error_msg', sa.String(length=300), nullable=True, comment='失败原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_translations_conversation_id'), 'voice_translations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_voice_translations_message_id'), 'voice_translations', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_translations_message_id'), table_name='voice_translations')
    op.drop_index(op.f('ix_voice_translations_conversation_id'), table_name='voice_translations')
    op.drop_table('voice_translations')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_plans_student_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_score_records_student_id'), table_name='score_records')
    op.drop_table('score_records')
    op.drop_index(op.f('ix_review_records_target_id'), table_name='review_records')
    op.drop_table('review_records')
    op.drop_index(op.f('ix_reminder_logs_reminder_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_patient_id'), table_name='reminder_logs')
    op.drop_table('reminder_logs')
    op.drop_index(op.f('ix_plan_todos_student_id'), table_name='plan_todos')
    op.drop_index(op.f('ix_plan_todos_plan_id'), table_name='plan_todos')
    op.drop_table('plan_todos')
    op.drop_index(op.f('ix_patient_profiles_user_id'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conv_time', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_medication_logs_patient_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_medical_histories_patient_id'), table_name='medical_histories')
    op.drop_table('medical_histories')
    op.drop_index(op.f('ix_health_reminders_patient_id'), table_name='health_reminders')
    op.drop_table('health_reminders')
    op.drop_index(op.f('ix_health_data_patient_id'), table_name='health_data')
    op.drop_table('health_data')
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_conversations_student_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_patient_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_doctor_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_consultation_summaries_student_id'), table_name='consultation_summaries')
    op.drop_index(op.f('ix_consultation_summaries_conversation_id'), table_name='consultation_summaries')
    op.drop_table('consultation_summaries')
    op.drop_index(op.f('ix_consultation_records_patient_id'), table_name='consultation_records')
    op.drop_index(op.f('ix_consultation_records_conversation_id'), table_name='consultation_records')
    op.drop_table('consultation_records')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
